### ISSUE TITLE
Resolvo is backtracking to a version that is disallowed by Root.

### ISSUE THREAD

**Issue by tdejager** [mamba-org/resolvo#23]
As mentioned in issue: https://github.com/prefix-dev/rip/issues/173

Resolvo, seems to be backtracking to a version that is not allowed. RIP implements a relatively straightforward `DependencyProvider` and integrates with Resolvo directly.

When trying to resolve: `apache-airflow[all]==2.8.1 apache-beam>=2.47`. The resolution gets to a point where we seem to be selecting a version that is explicitly disallowed by root: 

```
2024-01-25T19:59:26.200863Z ERROR rattler_installs_packages::index::package_database: Error from source distributions 'apache-beam-2.42.0.zip' skipped: 
````

Namely version **2.42.0**. We know for sure that this is a `get_dependencies` call and while `get_candidates` should be callable by the backtracking algorithm `get_dependencies` should only be called if there is a Partial Solution. This should not be possible because the selection of candidate **2.42.0** should never result in a Partial Solution, because the explicit root requirement cannot be satisfied.

Edit:

Also found this message in the logs

> 2024-01-26T15:14:22.352218Z  INFO resolvo::solver: deciding to assign apache-beam=2.42.0 with 45 candidates (required by <root>

Which seems weird because this version is not allowed by root.

**Comment by notatallshaw** [comment]
Sorry for wasting your time, this is a user error: https://github.com/prefix-dev/rip/issues/173#issuecomment-1912360720

**Comment by tdejager** [comment]
Good that would have been a strange bug!
