### ISSUE TITLE
Prefer solving for explicitly required dependencies first

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/resolvo#60]
In https://github.com/prefix-dev/pixi/issues/1708 it was noted that the solver does not prefer selecting explicitly requested packages. We should experiment with whether adding that to the decision heuristic is possible and doesn't affect performance too badly. 

My idea would be to prefer deciding on explicitly required dependencies _first_ before considering transitive dependencies.

@jjerphan @wolfv Do you have thoughts? Have you experimented with this before?

**Comment by traversaro** [comment]
To provide a bit more context from https://github.com/prefix-dev/pixi/issues/1708 : I guess this could be a point of confusion for people migrating from conda, where (if I am not wrong) this is taked into account.

**Comment by jjerphan** [comment]
Thank you for opening the discussion.

I have not explored it yet, but I think it is worth it.

**Comment by jjerphan** [comment]
How about tacking https://github.com/conda/conda/issues/13861 first or in parallel?

**Comment by jjerphan** [comment]
Similarly to conda as pointed out by Jaime in https://github.com/mamba-org/resolvo/issues/60#issuecomment-2284082332, [`mamba` defines a custom comparable](https://github.com/mamba-org/mamba/blob/d17ebc52cc70894576df4299fe2426f943071347/libmamba/src/solver/libsolv/solver.cpp#L28-L51) to [sort `MatchSpec` before solving the problems](https://github.com/mamba-org/mamba/blob/d17ebc52cc70894576df4299fe2426f943071347/libmamba/src/solver/libsolv/solver.cpp#L88-L106)

**Comment by traversaro** [comment]
Thanks @baszalmstra !
